config/routes.rb
Accounting::Application.routes.draw do
  resources :companies

  resources :revenues

  resources :expenses

  root 'welcome#index'

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :revenues
  has_many :expenses

  accepts_nested_attributes_for :revenues
  accepts_nested_attributes_for :expenses

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  self.inheritance_column = nil
  
  belongs_to :company
end

app/models/revenue.rb
class Revenue < ActiveRecord::Base
  self.inheritance_column = nil

  belongs_to :company

  def amount
    "$%.2f" % self[:amount]
  end  

  def fee
    "$%.2f" % self[:fee]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :main_contact, :phone, :email, :website, :address, :city, :state, :zip, :country, revenues_attributes: [:id, :description, :amount, :fee, :date, :type], expenses_attributes: [:id, :description, :amount, :date, :type])
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render action: 'show', status: :created, location: @expense }
      else
        format.html { render action: 'new' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:description, :amount, :date, :type, :company_id)
    end
end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController
  before_action :set_revenue, only: [:show, :edit, :update, :destroy]

  # GET /revenues
  # GET /revenues.json
  def index
    @revenues = Revenue.all
  end

  # GET /revenues/1
  # GET /revenues/1.json
  def show
  end

  # GET /revenues/new
  def new
    @revenue = Revenue.new
  end

  # GET /revenues/1/edit
  def edit
  end

  # POST /revenues
  # POST /revenues.json
  def create
    @revenue = Revenue.new(revenue_params)

    respond_to do |format|
      if @revenue.save
        format.html { redirect_to @revenue, notice: 'Revenue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @revenue }
      else
        format.html { render action: 'new' }
        format.json { render json: @revenue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /revenues/1
  # PATCH/PUT /revenues/1.json
  def update
    respond_to do |format|
      if @revenue.update(revenue_params)
        format.html { redirect_to @revenue, notice: 'Revenue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @revenue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revenues/1
  # DELETE /revenues/1.json
  def destroy
    @revenue.destroy
    respond_to do |format|
      format.html { redirect_to revenues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_revenue
      @revenue = Revenue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def revenue_params
      params.require(:revenue).permit(:description, :amount, :date, :type, :fee, :company_id)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s, f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/revenues_helper.rb
module RevenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_expenses.html.erb
<fieldset>
  <%= f.text_area :description, placeholder: "Expense Description" %>
  <%= f.text_field :amount, placeholder: "Expense Amount" %>
  <%= f.text_field :date, placeholder: "Expense Date", class: "date" %>
  <%= f.select(:type, ['Software', 'Infrastructure', 'Custom'], :prompt => "Select Type" ) %>
  <%= f.hidden_field :_destroy %>
  <%= link_to '[remove]', '#', class: 'remove_fields' %>
</fieldset>

app/views/companies/_form.html.erb
<div id="container" style="width:500px">
  <%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

    <ul>
      <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div style="width:250px;float:left;">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :main_contact %><br>
      <%= f.text_field :main_contact %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :website %><br>
      <%= f.text_field :website %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :state %><br>
      <%= f.text_field :state %>
    </div>
    <div class="field">
      <%= f.label :zip %><br>
      <%= f.text_field :zip %>
    </div>
    <div class="field">
      <%= f.label :country %><br>
      <%= f.country_select :country, ['Select Country'] %>
    </div>
  </div>
  <div style="width:250px;float:left;">


    <div class="form-group">
      <%= f.fields_for :revenues do |builder| %>
      <%= render 'revenues', f: builder %>
      <% end %>
    </div>
    <div class="actions">
      <%= link_to_add_fields "Add Revenue", f, :revenues %>
    </div>

    <div class="form-group">
      <%= f.fields_for :expenses do |builder| %>
      <%= render 'expenses', f: builder %>
      <% end %>
    </div>
    <div class="actions">
      <%= link_to_add_fields "Add Expense", f, :expenses %>
    </div>

  </div>

  <div style="clear:both;">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <% end %>
</div>

app/views/companies/_revenues.html.erb
<fieldset>
  <%= f.text_area :description, placeholder: "Revenue Description" %>
  <%= f.text_field :amount, placeholder: "Revenue Amount" %>
  <%= f.text_field :fee, placeholder: "Revenue Fee" %>
  <%= f.text_field :date, placeholder: "Revenue Date", class: "date" %>
  <%= f.select(:type, ['Sale', 'Service', 'Custom'], :prompt => "Select Type" ) %>
  <%= f.hidden_field :_destroy %>
  <%= link_to '[remove]', '#', class: 'remove_fields' %>
</fieldset>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Main contact</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Website</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.main_contact %></td>
        <td><%= company.phone %></td>
        <td><%= company.email %></td>
        <td><%= company.website %></td>
        <td><%= company.address %></td>
        <td><%= company.city %></td>
        <td><%= company.state %></td>
        <td><%= company.zip %></td>
        <td><%= company.country %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Main contact:</strong>
  <%= @company.main_contact %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @company.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @company.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @company.zip %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
<% if @expense.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

  <ul>
    <% @expense.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>

<%= f.collection_select :company_id, Company.order('name ASC').all, :id, :name, :prompt => "Select Company" %>

<div class="field">
  <%= f.label :amount %><br>
  <%= f.text_field :amount %>
</div>
<div class="field">
  <%= f.label :date %><br>
  <%= f.text_field :date, class: "date" %>
</div>
<div class="field">
  <%= f.label :type %><br>
  <%= f.select(:type, ['Software', 'Infrastructure', 'Custom'], :prompt => "Select Type" ) %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table id="expense" class="display">
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Date</th>
      <th>Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
    <tr>
      <td><%= expense.description %></td>
      <td><%= number_to_currency expense.amount %></td>
      <td><%= expense.date %></td>
      <td><%= expense.type %></td>
      <td><%= link_to 'Show', expense %></td>
      <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
      <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<table>
  <thead>
    <tr>
     <th>Total</th>
   </tr>
 </thead>
 <tbody>
  <tr>
    <td><%= number_to_currency @expenses.inject(0) {|sum, hash| sum + hash[:amount]} %></td>
  </tr>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Type:</strong>
  <%= @expense.type %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/layouts/_header.html.erb
<%= link_to 'Revenues', revenues_path %>
<%= link_to 'Expenses', expenses_path %>
<%= link_to 'Companies', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accounting</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/revenues/_form.html.erb
<%= form_for(@revenue) do |f| %>
  <% if @revenue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@revenue.errors.count, "error") %> prohibited this revenue from being saved:</h2>

      <ul>
      <% @revenue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= f.collection_select :company_id, Company.order('name ASC').all, :id, :name, :prompt => "Select Company" %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label 'Fees' %><br>
    <%= f.text_field :fee %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, class: "date" %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.select(:type, ['Sale', 'Service', 'Custom'], :prompt => "Select Type" ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/revenues/edit.html.erb
<h1>Editing revenue</h1>

<%= render 'form' %>

<%= link_to 'Show', @revenue %> |
<%= link_to 'Back', revenues_path %>

app/views/revenues/index.html.erb
<h1>Revenue</h1>

<%= line_chart @revenues.group_by_month(:date).sum(:amount) %>

<table id="revenue" class="display">
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Description</th>
      <th>Amount</th>
      <th>Fees</th>
      <th>Type</th>
    </tr>
  </thead>

  <tbody>
    <% @revenues.each do |revenue| %>
    <tr>
      <td><%= link_to revenue.date, revenue %></td>
      <td><%= link_to revenue.company.name, revenue.company %></td>
      <td><%= truncate revenue.description, length: 40 %></td>
      <td><%= revenue.amount %></td>
      <td><%= revenue.fee %></td>
      <td><%= revenue.type %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<table>
  <thead>
    <tr>
     <th>Amount</th>
     <th>-&nbsp; Fee</th>
     <th>=&nbsp; Total</th>
   </tr>
 </thead>
 <tbody>
  <tr>
  <td>$<%= amount_total = @revenues.inject(0) {|sum, hash| sum + hash[:amount]} %></td>
  <td>&nbsp;-&nbsp;$<%= fee_total = @revenues.inject(0) {|sum, hash| sum + hash[:fee]} %></td>
  <td>&nbsp;=&nbsp;$<%= amount_total - fee_total %></td>
</tr>
</tbody>
</table>
<br>

<%= link_to 'New Revenue', new_revenue_path %>

app/views/revenues/new.html.erb
<h1>New revenue</h1>

<%= render 'form' %>

<%= link_to 'Back', revenues_path %>

app/views/revenues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @revenue.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @revenue.company.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @revenue.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @revenue.date %>
</p>

<p>
  <strong>Type:</strong>
  <%= @revenue.type %>
</p>

<%= link_to 'New', new_revenue_path %> |
<%= link_to 'Edit', edit_revenue_path(@revenue) %> |
<%= link_to 'Back', revenues_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>